myapp:
  currencies:
    AUD: 2
    CAD: 2
    CNY: 2
    CZK: 2
    DKK: 2
    EUR: 2
    GBP: 2
    JPY: 0
    NOK: 2
    NZD: 2
    USD: 2
  conversionRates:
    AUDUSD: 0.8371
    CADUSD: 0.8711
    USDCNY: 6.1715
    EURUSD: 1.2315
    GBPUSD: 1.5683
    NZDUSD: 0.7750
    USDJPY: 119.95
    EURCZK: 27.6028
    EURDKK: 7.4405
    EURNOK: 8.6651
